name: OWASP ZAP Full Scan

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP ZAP full scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'https://vulnerable-web-app-juanparra-d1e6880be163.herokuapp.com/'
          cmd_options: '-a'  # Activar escaneo activo
          upload_artifact: false  # ✅ Desactiva subida automática que genera error

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-full-report
          path: report_html.html
