name: OWASP ZAP Full Scan

on:
  workflow_dispatch:

permissions:
  issues: write
  contents: read

jobs:
  zap_full_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP ZAP full scan
        uses: zaproxy/action-full-scan@v0.10.0
        with:
          target: 'https://vulnerable-web-app-juanparra-d1e6880be163.herokuapp.com/'
          cmd_options: '-a'
          allow_issue_writing: true
          upload_artifact: false  

      - name: List files to confirm report exists
        run: ls -la
